### ISSUE TITLE
Give the regular expression in SW-Application/main.js a global flag

### ISSUE THREAD

**Issue by AlexHoorn** [raadjoe/knowledge-data-vu#2]
On line [10 in `main.js`](https://github.com/raadjoe/knowledge-data-vu/blob/9c1ef46f4858f5af8fab3cce0883dd702c808c19/Tutorials/SW-Application/main.js#L10) the `.replace()` function uses a regular expression. The current expression looks for the first occurrence of a `#` and is then satisfied. However, it can occur that a student has multiple instances of `#` that have to be encoded. E.g. when using both *rdf* and *rdfs* in a query.

This gives a confusing error such as `Virtuoso 37000 Error SP030: SPARQL compiler, line 1: Missing <namespace-iri-string> in PREFIX declaration at '<' before 'http:'` even though the query seems fine and runs in any other external interface such as Yasgui.

See question [335](https://piazza.com/class/kcynmqh7f7g5pn?cid=335) on Piazza to see a relevant occurrence of this problem.

A very simple fix could be giving the expression a *global* flag. Replace `/#/` with `/#/g` and that will fix this specific problem. I'm assuming this repository is not the actual source of your storage for the current and upcoming years. So I'm simply opening an issue instead of a PR.

**Comment by raadjoe** [comment]
Thanks a lot Alex for noticing this issue and providing the solution! I updated the main.js file with your solution.
